"""empty message

Revision ID: 383a24e862a8
Revises: a31476ab5938
Create Date: 2018-10-17 15:39:44.522464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383a24e862a8'
down_revision = 'a31476ab5938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'state')
    # ### end Alembic commands ###
