"""empty message

Revision ID: 62078b2765d9
Revises: 383a24e862a8
Create Date: 2018-10-18 11:15:26.607758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62078b2765d9'
down_revision = '383a24e862a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
